"""Added deafault currency/exchange rate to euro column 

Revision ID: 07e279e4e353
Revises: 560e49007bb9
Create Date: 2025-10-29 18:36:00.885248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e279e4e353'
down_revision = '560e49007bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate_to_euro', sa.Float(), nullable=True))
        batch_op.drop_column('exchange_rate_to_default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate_to_default', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('exchange_rate_to_euro')

    # ### end Alembic commands ###
