"""Added deafault currency/exchange table 

Revision ID: 560e49007bb9
Revises: c1a6260466c0
Create Date: 2025-10-29 14:34:47.924180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560e49007bb9'
down_revision = 'c1a6260466c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate_to_default', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate_to_default')

    # ### end Alembic commands ###
