"""Added deafault currency for user

Revision ID: c1a6260466c0
Revises: 6084a1e54364
Create Date: 2025-10-29 12:51:44.623027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a6260466c0'
down_revision = '6084a1e54364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_default_currency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'currency', ['user_default_currency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_default_currency_id')

    # ### end Alembic commands ###
