"""Added curency table

Revision ID: 6084a1e54364
Revises: 15bc546a0c86
Create Date: 2025-10-27 12:01:15.144805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6084a1e54364'
down_revision = '15bc546a0c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'currency', ['currency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('currency_id')

    op.drop_table('currency')
    # ### end Alembic commands ###
